version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: helpmate_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helpmate
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: